/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    resume: Resume;
    'career-application': CareerApplication;
    'agent-career-application': AgentCareerApplication;
    pages: Page;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    resume: ResumeSelect<false> | ResumeSelect<true>;
    'career-application': CareerApplicationSelect<false> | CareerApplicationSelect<true>;
    'agent-career-application': AgentCareerApplicationSelect<false> | AgentCareerApplicationSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Temporary until document saves successfully
   */
  temporary?: boolean | null;
  ownerCollection?: string | null;
  ownerDocId?: string | null;
  ownerField?: string | null;
  derivedFrom?: (string | null) | Media;
  blurDataURL?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume".
 */
export interface Resume {
  id: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-application".
 */
export interface CareerApplication {
  id: string;
  name: string;
  phone: string;
  email: string;
  position: string;
  message: string;
  resume: string | Resume;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-career-application".
 */
export interface AgentCareerApplication {
  id: string;
  name: string;
  phone: string;
  resume: string | Resume;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  uploadSessionId?: string | null;
  name: string;
  slug: string;
  layout: (
    | {
        uploadSessionId?: string | null;
        heroes: {
          image: string | Media;
          /**
           * Title (English). Max 120 characters.
           */
          title: string;
          /**
           * শিরোনাম (বাংলা)। সর্বোচ্চ ১২০ অক্ষর।
           */
          titleBN: string;
          /**
           * Subtitle (English). Max 160 characters.
           */
          subtitle?: string | null;
          /**
           * উপশিরোনাম (বাংলা)। সর্বোচ্চ ১৬০ অক্ষর।
           */
          subtitleBN?: string | null;
          description?: {
            root: {
              type: string;
              children: {
                type: string;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          descriptionBN?: {
            root: {
              type: string;
              children: {
                type: string;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          id?: string | null;
        }[];
        /**
         * Add call-to-action buttons that appear below the hero content (maximum 2 buttons)
         */
        ctaButtons?:
          | (
              | {
                  /**
                   * Max 24 characters.
                   */
                  label: string;
                  /**
                   * সর্বোচ্চ 24 অক্ষর।
                   */
                  labelBN: string;
                  /**
                   * Enter the page path only (no domain). Example: "/plans" or "/premium-calculator".
                   */
                  page: string;
                  style?: ('primary' | 'glass') | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'pageLink';
                }
              | {
                  /**
                   * Max 24 characters.
                   */
                  label: string;
                  /**
                   * সর্বোচ্চ 24 অক্ষর।
                   */
                  labelBN: string;
                  /**
                   * Paste a YouTube link (watch, share, or embed). Example: https://www.youtube.com/watch?v=XXXX or https://youtu.be/XXXX
                   */
                  youtubeUrl: string;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'youtubeVideo';
                }
              | {
                  /**
                   * Max 24 characters.
                   */
                  label: string;
                  /**
                   * সর্বোচ্চ 24 অক্ষর।
                   */
                  labelBN: string;
                  /**
                   * Example: +88 09610889900
                   */
                  phoneNumber: string;
                  style?: ('primary' | 'glass') | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'callNow';
                }
            )[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        /**
         * Hex color in #RRGGBB (e.g., #FFFFFF). Length 7 (৭).
         */
        backgroundColor?: string | null;
        /**
         * Short label above the main title. Max 40 characters.
         */
        heading: string;
        /**
         * মূল শিরোনামের উপরে ছোট লেবেল। সর্বোচ্চ ৪০ অক্ষর।
         */
        headingBN: string;
        /**
         * Primary headline for the section. Max 80 characters.
         */
        title: string;
        /**
         * এই সেকশনের মূল শিরোনাম। সর্বোচ্চ ৮০ অক্ষর।
         */
        titleBN: string;
        /**
         * Supporting line under the main title. Max 120 characters.
         */
        subtitle: string;
        /**
         * মূল শিরোনামের নিচে সহায়ক লাইন। সর্বোচ্চ ১২০ অক্ষর।
         */
        subtitleBN: string;
        /**
         * Optional. Must appear verbatim inside the Subtitle. Max 40 characters.
         */
        highlightedText?: string | null;
        /**
         * ঐচ্ছিক। সাবটাইটেলের ভেতরে হুবহু থাকতে হবে। সর্বোচ্চ ৪০ অক্ষর।
         */
        highlightedTextBN?: string | null;
        /**
         * 2–3 short sentences about why customers choose us. Max 300 characters.
         */
        description: string;
        /**
         * গ্রাহকরা কেন আমাদের বেছে নেন—এই বিষয়ে ২–৩টি সংক্ষিপ্ত বাক্য লিখুন। সর্বোচ্চ ৩০০ অক্ষর।
         */
        descriptionBN: string;
        /**
         * Used as the background on mobile; on larger screens it appears on the left side. Recommended aspect ratio 16:9; ~200KB.
         */
        mainImage?: (string | null) | Media;
        /**
         * Shown left of the statistics on desktop. Recommended aspect ratio 4:5; ~100KB.
         */
        sideImage?: (string | null) | Media;
        /**
         * Provide exactly four highlights (e.g., Settlement Rate, Branches, Years of Service, Happy Customers).
         */
        stats: {
          /**
           * Upload a small square icon (1:1).
           */
          icon?: (string | null) | Media;
          /**
           * Short descriptive label. Allowed: letters, numbers, spaces, "&", "-", "/". Max 32 characters.
           */
          label: string;
          /**
           * সংক্ষিপ্ত বর্ণনামূলক লেবেল। ব্যবহারযোগ্য: অক্ষর, সংখ্যা, স্পেস, “&”, “-”, “/”। সর্বোচ্চ ৩২ অক্ষর।
           */
          labelBN: string;
          /**
           * e.g., 100%, 112+, 25 yrs, 1.2M+, 3,000+, 98.5%. Max 16 characters.
           */
          value: string;
          /**
           * যেমন: 100%, 112+, 25 yrs, 1.2M+, 3,000+, 98.5%। সর্বোচ্চ ১৬ অক্ষর।
           */
          valueBN: string;
          id?: string | null;
        }[];
        /**
         * Text shown on the call-to-action button. Max 24 characters.
         */
        buttonText?: string | null;
        /**
         * কলে-টু-অ্যাকশন বাটনে দেখানো টেক্সট। সর্বোচ্চ ২৪ অক্ষর।
         */
        buttonTextBN?: string | null;
        /**
         * Provide only if you want a clickable CTA. If CTA Text is set, this becomes required. Must be an internal path (e.g., /about-us) or a full http(s) URL. Max 100 characters.
         */
        buttonLink?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'why-choose-us';
      }
    | {
        /**
         * Hex color in #RRGGBB (e.g., #FFFFFF). Length 7 (৭).
         */
        backgroundColor?: string | null;
        /**
         * Short label above the main title. Max 40 characters.
         */
        heading: string;
        /**
         * মূল শিরোনামের উপরে ছোট লেবেল। সর্বোচ্চ ৪০ অক্ষর।
         */
        headingBN: string;
        /**
         * Primary headline for the section. Max 80 characters.
         */
        title: string;
        /**
         * সেকশনের প্রধান শিরোনাম। সর্বোচ্চ ৮০ অক্ষর।
         */
        titleBN: string;
        /**
         * Optional. Must appear verbatim inside the Title. Max 40 characters.
         */
        highlightedText?: string | null;
        /**
         * ঐচ্ছিক। অবশ্যই শিরোনামের ভিতর হুবহু থাকতে হবে। সর্বোচ্চ ৪০ অক্ষর।
         */
        highlightedTextBN?: string | null;
        /**
         * 2–3 short sentences about plans. Max 300 characters.
         */
        description: string;
        /**
         * প্ল্যান সম্পর্কে ২–৩টি সংক্ষিপ্ত বাক্য। সর্বোচ্চ ৩০০ অক্ষর।
         */
        descriptionBN: string;
        /**
         * Add 3–5 plans to feature on the homepage.
         */
        plans: {
          /**
           * Plan icon. Recommended aspect ratio 1:1; ~50KB.
           */
          icon?: (string | null) | Media;
          /**
           * Plan image. Recommended aspect ratio ~451:350 (≈1.2886). Keep under ~100KB when possible.
           */
          image?: (string | null) | Media;
          /**
           * Main plan title. Max 20 characters.
           */
          title: string;
          /**
           * প্রধান প্ল্যান টাইটেল। সর্বোচ্চ ২০ অক্ষর।
           */
          titleBN: string;
          /**
           * Secondary plan title. Max 80 characters.
           */
          subtitle: string;
          /**
           * দ্বিতীয় প্ল্যান টাইটেল। সর্বোচ্চ ৮০ অক্ষর।
           */
          subtitleBN: string;
          /**
           * Brief description of the plan. Max 300 characters.
           */
          description: string;
          /**
           * প্ল্যানের সংক্ষিপ্ত বর্ণনা। সর্বোচ্চ ৩০০ অক্ষর।
           */
          descriptionBN: string;
          /**
           * Text shown on the plan’s call-to-action button. Max 24 characters.
           */
          plansButtonText?: string | null;
          /**
           * কলে-টু-অ্যাকশন বাটনে দেখানো টেক্সট। সর্বোচ্চ ২৪ অক্ষর।
           */
          plansButtonTextBN?: string | null;
          /**
           * Provide only if you want a clickable button for this plan. If Plans Button Text is set, this becomes required. Must be an internal path (e.g., /plans/xyz) or a full http(s) URL. Max 100 characters.
           */
          plansButtonLink?: string | null;
          id?: string | null;
        }[];
        /**
         * Text shown on the call-to-action button. Max 24 characters.
         */
        buttonText?: string | null;
        /**
         * কলে-টু-অ্যাকশন বাটনে দেখানো টেক্সট। সর্বোচ্চ ২৪ অক্ষর।
         */
        buttonTextBN?: string | null;
        /**
         * Provide only if you want a clickable CTA. If CTA Text is set, this becomes required. Must be an internal path (e.g., /about-us) or a full http(s) URL. Max 100 characters.
         */
        buttonLink?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'featured-plans';
      }
  )[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'resume';
        value: string | Resume;
      } | null)
    | ({
        relationTo: 'career-application';
        value: string | CareerApplication;
      } | null)
    | ({
        relationTo: 'agent-career-application';
        value: string | AgentCareerApplication;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  temporary?: T;
  ownerCollection?: T;
  ownerDocId?: T;
  ownerField?: T;
  derivedFrom?: T;
  blurDataURL?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume_select".
 */
export interface ResumeSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-application_select".
 */
export interface CareerApplicationSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  position?: T;
  message?: T;
  resume?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-career-application_select".
 */
export interface AgentCareerApplicationSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  resume?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  uploadSessionId?: T;
  name?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              uploadSessionId?: T;
              heroes?:
                | T
                | {
                    image?: T;
                    title?: T;
                    titleBN?: T;
                    subtitle?: T;
                    subtitleBN?: T;
                    description?: T;
                    descriptionBN?: T;
                    id?: T;
                  };
              ctaButtons?:
                | T
                | {
                    pageLink?:
                      | T
                      | {
                          label?: T;
                          labelBN?: T;
                          page?: T;
                          style?: T;
                          id?: T;
                          blockName?: T;
                        };
                    youtubeVideo?:
                      | T
                      | {
                          label?: T;
                          labelBN?: T;
                          youtubeUrl?: T;
                          id?: T;
                          blockName?: T;
                        };
                    callNow?:
                      | T
                      | {
                          label?: T;
                          labelBN?: T;
                          phoneNumber?: T;
                          style?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        'why-choose-us'?:
          | T
          | {
              backgroundColor?: T;
              heading?: T;
              headingBN?: T;
              title?: T;
              titleBN?: T;
              subtitle?: T;
              subtitleBN?: T;
              highlightedText?: T;
              highlightedTextBN?: T;
              description?: T;
              descriptionBN?: T;
              mainImage?: T;
              sideImage?: T;
              stats?:
                | T
                | {
                    icon?: T;
                    label?: T;
                    labelBN?: T;
                    value?: T;
                    valueBN?: T;
                    id?: T;
                  };
              buttonText?: T;
              buttonTextBN?: T;
              buttonLink?: T;
              id?: T;
              blockName?: T;
            };
        'featured-plans'?:
          | T
          | {
              backgroundColor?: T;
              heading?: T;
              headingBN?: T;
              title?: T;
              titleBN?: T;
              highlightedText?: T;
              highlightedTextBN?: T;
              description?: T;
              descriptionBN?: T;
              plans?:
                | T
                | {
                    icon?: T;
                    image?: T;
                    title?: T;
                    titleBN?: T;
                    subtitle?: T;
                    subtitleBN?: T;
                    description?: T;
                    descriptionBN?: T;
                    plansButtonText?: T;
                    plansButtonTextBN?: T;
                    plansButtonLink?: T;
                    id?: T;
                  };
              buttonText?: T;
              buttonTextBN?: T;
              buttonLink?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}