/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    resume: Resume;
    'career-application': CareerApplication;
    'agent-career-application': AgentCareerApplication;
    pages: Page;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    resume: ResumeSelect<false> | ResumeSelect<true>;
    'career-application': CareerApplicationSelect<false> | CareerApplicationSelect<true>;
    'agent-career-application': AgentCareerApplicationSelect<false> | AgentCareerApplicationSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    'global-header': GlobalHeader;
    'global-navbar': GlobalNavbar;
    'global-footer': GlobalFooter;
  };
  globalsSelect: {
    'global-header': GlobalHeaderSelect<false> | GlobalHeaderSelect<true>;
    'global-navbar': GlobalNavbarSelect<false> | GlobalNavbarSelect<true>;
    'global-footer': GlobalFooterSelect<false> | GlobalFooterSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Temporary until document saves successfully
   */
  temporary?: boolean | null;
  ownerCollection?: string | null;
  ownerDocId?: string | null;
  ownerField?: string | null;
  derivedFrom?: (string | null) | Media;
  blurDataURL?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume".
 */
export interface Resume {
  id: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-application".
 */
export interface CareerApplication {
  id: string;
  name: string;
  phone: string;
  email: string;
  position: string;
  message: string;
  resume: string | Resume;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-career-application".
 */
export interface AgentCareerApplication {
  id: string;
  name: string;
  phone: string;
  resume: string | Resume;
  updatedAt: string;
  createdAt: string;
}
/**
 * Dynamic pages assembled from blocks
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  uploadSessionId?: string | null;
  name: string;
  slug: string;
  /**
   * Uncheck to hide this page (404).
   */
  publish?: boolean | null;
  layout: (
    | {
        uploadSessionId?: string | null;
        heroes: {
          image: string | Media;
          /**
           * Title (English). Max 120 characters.
           */
          title: string;
          /**
           * শিরোনাম (বাংলা)। সর্বোচ্চ ১২০ অক্ষর।
           */
          titleBN: string;
          /**
           * Subtitle (English). Max 160 characters.
           */
          subtitle?: string | null;
          /**
           * উপশিরোনাম (বাংলা)। সর্বোচ্চ ১৬০ অক্ষর।
           */
          subtitleBN?: string | null;
          description?: {
            root: {
              type: string;
              children: {
                type: string;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          descriptionBN?: {
            root: {
              type: string;
              children: {
                type: string;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          id?: string | null;
        }[];
        /**
         * Add call-to-action buttons that appear below the hero content (maximum 2 buttons)
         */
        ctaButtons?:
          | (
              | {
                  /**
                   * Max 24 characters.
                   */
                  label: string;
                  /**
                   * সর্বোচ্চ 24 অক্ষর।
                   */
                  labelBN: string;
                  /**
                   * Enter the page path only (no domain). Example: "/plans" or "/premium-calculator".
                   */
                  page: string;
                  style?: ('primary' | 'glass') | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'pageLink';
                }
              | {
                  /**
                   * Max 24 characters.
                   */
                  label: string;
                  /**
                   * সর্বোচ্চ 24 অক্ষর।
                   */
                  labelBN: string;
                  /**
                   * Paste a YouTube link (watch, share, or embed). Example: https://www.youtube.com/watch?v=XXXX or https://youtu.be/XXXX
                   */
                  youtubeUrl: string;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'youtubeVideo';
                }
              | {
                  /**
                   * Max 24 characters.
                   */
                  label: string;
                  /**
                   * সর্বোচ্চ 24 অক্ষর।
                   */
                  labelBN: string;
                  /**
                   * Example: +88 09610889900
                   */
                  phoneNumber: string;
                  style?: ('primary' | 'glass') | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'callNow';
                }
            )[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        /**
         * Hex color in #RRGGBB (e.g., #FFFFFF). Length 7 (৭).
         */
        backgroundColor?: string | null;
        /**
         * Short label above the main title. Max 40 characters.
         */
        heading: string;
        /**
         * মূল শিরোনামের উপরে ছোট লেবেল। সর্বোচ্চ ৪০ অক্ষর।
         */
        headingBN: string;
        /**
         * Primary headline for the section. Max 80 characters.
         */
        title: string;
        /**
         * এই সেকশনের মূল শিরোনাম। সর্বোচ্চ ৮০ অক্ষর।
         */
        titleBN: string;
        /**
         * Supporting line under the main title. Max 120 characters.
         */
        subtitle: string;
        /**
         * মূল শিরোনামের নিচে সহায়ক লাইন। সর্বোচ্চ ১২০ অক্ষর।
         */
        subtitleBN: string;
        /**
         * Optional. Must appear verbatim inside the Subtitle. Max 40 characters.
         */
        highlightedText?: string | null;
        /**
         * ঐচ্ছিক। সাবটাইটেলের ভেতরে হুবহু থাকতে হবে। সর্বোচ্চ ৪০ অক্ষর।
         */
        highlightedTextBN?: string | null;
        /**
         * 2–3 short sentences about why customers choose us. Max 300 characters.
         */
        description: string;
        /**
         * গ্রাহকরা কেন আমাদের বেছে নেন—এই বিষয়ে ২–৩টি সংক্ষিপ্ত বাক্য লিখুন। সর্বোচ্চ ৩০০ অক্ষর।
         */
        descriptionBN: string;
        /**
         * Used as the background on mobile; on larger screens it appears on the left side. Recommended aspect ratio 16:9; ~200KB.
         */
        mainImage: string | Media;
        /**
         * Shown left of the statistics on desktop. Recommended aspect ratio 4:5; ~100KB.
         */
        sideImage: string | Media;
        /**
         * Provide exactly four highlights (e.g., Settlement Rate, Branches, Years of Service, Happy Customers).
         */
        stats: {
          /**
           * Upload a small square icon (1:1).
           */
          icon: string | Media;
          /**
           * Short descriptive label. Allowed: letters, numbers, spaces, "&", "-", "/". Max 32 characters.
           */
          label: string;
          /**
           * সংক্ষিপ্ত বর্ণনামূলক লেবেল। ব্যবহারযোগ্য: অক্ষর, সংখ্যা, স্পেস, “&”, “-”, “/”। সর্বোচ্চ ৩২ অক্ষর।
           */
          labelBN: string;
          /**
           * e.g., 100%, 112+, 25 yrs, 1.2M+, 3,000+, 98.5%. Max 16 characters.
           */
          value: string;
          /**
           * যেমন: 100%, 112+, 25 yrs, 1.2M+, 3,000+, 98.5%। সর্বোচ্চ ১৬ অক্ষর।
           */
          valueBN: string;
          id?: string | null;
        }[];
        /**
         * Text shown on the call-to-action button. Max 24 characters.
         */
        buttonText?: string | null;
        /**
         * কলে-টু-অ্যাকশন বাটনে দেখানো টেক্সট। সর্বোচ্চ ২৪ অক্ষর।
         */
        buttonTextBN?: string | null;
        /**
         * Provide only if you want a clickable CTA. If CTA Text is set, this becomes required. Must be an internal path (e.g., /about-us) or a full http(s) URL. Max 100 characters.
         */
        buttonLink?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'why-choose-us';
      }
    | {
        /**
         * Hex color in #RRGGBB (e.g., #FFFFFF). Length 7 (৭).
         */
        backgroundColor?: string | null;
        /**
         * Short label above the main title. Max 40 characters.
         */
        heading: string;
        /**
         * মূল শিরোনামের উপরে ছোট লেবেল। সর্বোচ্চ ৪০ অক্ষর।
         */
        headingBN: string;
        /**
         * Primary headline for the section. Max 80 characters.
         */
        title: string;
        /**
         * সেকশনের প্রধান শিরোনাম। সর্বোচ্চ ৮০ অক্ষর।
         */
        titleBN: string;
        /**
         * Optional. Must appear verbatim inside the Title. Max 40 characters.
         */
        highlightedText?: string | null;
        /**
         * ঐচ্ছিক। অবশ্যই শিরোনামের ভিতর হুবহু থাকতে হবে। সর্বোচ্চ ৪০ অক্ষর।
         */
        highlightedTextBN?: string | null;
        /**
         * 2–3 short sentences about plans. Max 300 characters.
         */
        description: string;
        /**
         * প্ল্যান সম্পর্কে ২–৩টি সংক্ষিপ্ত বাক্য। সর্বোচ্চ ৩০০ অক্ষর।
         */
        descriptionBN: string;
        /**
         * Add 3–5 plans to feature on the homepage.
         */
        plans: {
          /**
           * Plan icon. Recommended aspect ratio 1:1; ~50KB.
           */
          icon: string | Media;
          /**
           * Plan image. Recommended aspect ratio ~451:350 (≈1.2886). Keep under ~100KB when possible.
           */
          image: string | Media;
          /**
           * Main plan title. Max 20 characters.
           */
          title: string;
          /**
           * প্রধান প্ল্যান টাইটেল। সর্বোচ্চ ২০ অক্ষর।
           */
          titleBN: string;
          /**
           * Secondary plan title. Max 80 characters.
           */
          subtitle: string;
          /**
           * দ্বিতীয় প্ল্যান টাইটেল। সর্বোচ্চ ৮০ অক্ষর।
           */
          subtitleBN: string;
          /**
           * Brief description of the plan. Max 300 characters.
           */
          description: string;
          /**
           * প্ল্যানের সংক্ষিপ্ত বর্ণনা। সর্বোচ্চ ৩০০ অক্ষর।
           */
          descriptionBN: string;
          /**
           * Text shown on the plan’s call-to-action button. Max 24 characters.
           */
          plansButtonText?: string | null;
          /**
           * কলে-টু-অ্যাকশন বাটনে দেখানো টেক্সট। সর্বোচ্চ ২৪ অক্ষর।
           */
          plansButtonTextBN?: string | null;
          /**
           * Provide only if you want a clickable button for this plan. If Plans Button Text is set, this becomes required. Must be an internal path (e.g., /plans/xyz) or a full http(s) URL. Max 100 characters.
           */
          plansButtonLink?: string | null;
          id?: string | null;
        }[];
        /**
         * Text shown on the call-to-action button. Max 24 characters.
         */
        buttonText?: string | null;
        /**
         * কলে-টু-অ্যাকশন বাটনে দেখানো টেক্সট। সর্বোচ্চ ২৪ অক্ষর।
         */
        buttonTextBN?: string | null;
        /**
         * Provide only if you want a clickable CTA. If CTA Text is set, this becomes required. Must be an internal path (e.g., /about-us) or a full http(s) URL. Max 100 characters.
         */
        buttonLink?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'featured-plans';
      }
    | {
        /**
         * Hex color in #RRGGBB (e.g., #FFFFFF). Length 7 (৭).
         */
        backgroundColor?: string | null;
        /**
         * Short label above the main title. Max 40 characters.
         */
        heading: string;
        /**
         * মূল শিরোনামের উপরে ছোট লেবেল। সর্বোচ্চ ৪০ অক্ষর।
         */
        headingBN: string;
        /**
         * Primary headline for the section. Max 40 characters.
         */
        title: string;
        /**
         * প্রধান শিরোনাম। সর্বোচ্চ ৪০ অক্ষর।
         */
        titleBN: string;
        /**
         * Optional. Must appear verbatim inside the Title. Max 40 characters.
         */
        highlightedText?: string | null;
        /**
         * ঐচ্ছিক। অবশ্যই শিরোনামের মধ্যে হুবহু থাকতে হবে। সর্বোচ্চ ৪০ অক্ষর।
         */
        highlightedTextBN?: string | null;
        /**
         * 1–2 short sentences describing the premium calculator. Max 200 characters.
         */
        description: string;
        /**
         * প্রিমিয়াম ক্যালকুলেটর সম্পর্কে ১–২টি সংক্ষিপ্ত বাক্য। সর্বোচ্চ ২০০ অক্ষর।
         */
        descriptionBN: string;
        /**
         * Primary background image (≈1.031:1 recommended). ~100KB preferred.
         */
        backgroundImage1: string | Media;
        /**
         * Secondary background image (≈1.031:1 recommended). ~100KB preferred.
         */
        backgroundImage2: string | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'home-premium-calculator';
      }
    | {
        /**
         * Hex color in #RRGGBB (e.g., #FFFFFF). Length 7 (৭).
         */
        backgroundColor?: string | null;
        /**
         * Short label above the main title. Max 40 characters.
         */
        sectionHeading: string;
        /**
         * মূল শিরোনামের উপরে ছোট লেবেল। সর্বোচ্চ ৪০ অক্ষর।
         */
        sectionHeadingBN: string;
        /**
         * Optional. Must appear verbatim inside the Section Heading. Max 40 characters.
         */
        sectionHeadingHighlightedText?: string | null;
        /**
         * ঐচ্ছিক। অবশ্যই সেকশন হেডিং-এর মধ্যে হুবহু থাকতে হবে। সর্বোচ্চ ৪০ অক্ষর।
         */
        sectionHeadingHighlightedTextBN?: string | null;
        /**
         * 1–3 content sections, each with a main image, video link, and 3 cards.
         */
        sections: {
          /**
           * Primary headline for this section. Max 80 characters.
           */
          title: string;
          /**
           * এই সেকশনের মূল শিরোনাম। সর্বোচ্চ ৮০ অক্ষর।
           */
          titleBN: string;
          /**
           * Optional. Must appear verbatim inside the Title. Max 40 characters.
           */
          titleHighlightedText?: string | null;
          /**
           * ঐচ্ছিক। অবশ্যই শিরোনামের মধ্যে হুবহু থাকতে হবে। সর্বোচ্চ ৪০ অক্ষর।
           */
          titleHighlightedTextBN?: string | null;
          /**
           * Supporting line under the title. Max 120 characters.
           */
          subtitle: string;
          /**
           * মূল শিরোনামের নিচে সহায়ক লাইন। সর্বোচ্চ ১২০ অক্ষর।
           */
          subtitleBN: string;
          /**
           * Use a YouTube URL (embed, watch, youtu.be, or youtube-nocookie). Max 200 characters.
           */
          mainVIdeoLink: string;
          /**
           * Large hero/thumbnail for this section. 4:3 recommended; ~100KB.
           */
          mainImage: string | Media;
          /**
           * Exactly 3 cards per section.
           */
          insuranceCardData?:
            | {
                /**
                 * Primary thumbnail for the card. 4:3 recommended; ~100KB.
                 */
                image: string | Media;
                /**
                 * Short heading for the card. Max 60 characters.
                 */
                title?: string | null;
                /**
                 * কার্ডের সংক্ষিপ্ত শিরোনাম। সর্বোচ্চ ৬০ অক্ষর।
                 */
                titleBN?: string | null;
                /**
                 * Short supporting copy. Max 200 characters.
                 */
                description?: string | null;
                /**
                 * সংক্ষিপ্ত সহায়ক বর্ণনা। সর্বোচ্চ ২০০ অক্ষর।
                 */
                descriptionBN?: string | null;
                /**
                 * Use a YouTube URL (embed, watch, youtu.be, or youtube-nocookie). Max 200 characters.
                 */
                videoLink: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'life-insurance-simplified';
      }
    | {
        /**
         * Hex color in #RRGGBB (e.g., #FFFFFF). Length 7 (৭).
         */
        backgroundColor?: string | null;
        /**
         * Primary heading. Max 80 (৮০) characters.
         */
        title: string;
        /**
         * প্রধান শিরোনাম। সর্বোচ্চ ৮০ অক্ষর।
         */
        titleBN: string;
        /**
         * Optional. Must appear verbatim inside the title. Max 40 (৪০) characters.
         */
        highlightedText?: string | null;
        /**
         * ঐচ্ছিক। শিরোনামের ভেতরে হুবহু থাকতে হবে। সর্বোচ্চ ৪০ অক্ষর।
         */
        highlightedTextBN?: string | null;
        /**
         * Absolute http(s) video URL (MP4/WebM/HLS). Max 300 (৩০০) chars.
         */
        backgroundVideoUrl: string;
        /**
         * youtube.com / youtu.be / youtube-nocookie.com only. Max 300 (৩০০) chars.
         */
        youtubeUrl: string;
        /**
         * Button label. Max 24 (২৪) characters.
         */
        youtubeButtonText: string;
        /**
         * বাটনের লেবেল। সর্বোচ্চ ২৪ অক্ষর।
         */
        youtubeButtonTextBN: string;
        /**
         * Poster/thumbnail for the background video (16:9 recommended, ~300KB).
         */
        thumbnail: string | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'home-video';
      }
    | {
        /**
         * Hex color in #RRGGBB (e.g., #FFFFFF). Length 7 (৭).
         */
        backgroundColor?: string | null;
        /**
         * Primary headline. Max 80 characters.
         */
        title: string;
        /**
         * প্রধান শিরোনাম। সর্বোচ্চ ৮০ অক্ষর।
         */
        titleBN: string;
        /**
         * Supporting line. Max 120 characters.
         */
        subtitle: string;
        /**
         * সহায়ক লাইন। সর্বোচ্চ ১২০ অক্ষর।
         */
        subtitleBN: string;
        /**
         * Optional. Must appear verbatim inside the Subtitle. Max 40 characters.
         */
        highlightedSubtitle?: string | null;
        /**
         * ঐচ্ছিক। অবশ্যই সাবটাইটেলের মধ্যে হুবহু থাকতে হবে। সর্বোচ্চ ৪০ অক্ষর।
         */
        highlightedSubtitleBN?: string | null;
        description: string;
        descriptionBN: string;
        /**
         * Optional. Max 24 characters.
         */
        buttonText?: string | null;
        /**
         * ঐচ্ছিক। সর্বোচ্চ ২৪ অক্ষর।
         */
        buttonTextBN?: string | null;
        /**
         * Required if CTA text is set. Internal path (e.g., /careers) or http(s) URL. Max 100 characters.
         */
        buttonLink?: string | null;
        /**
         * Displayed above the CTA button for this section. Recommended 16:9, ~200KB.
         */
        backgroundImage: string | Media;
        /**
         * Add 10–20 images that showcase life at Shanta.
         */
        gallery: {
          /**
           * Shown in the grid. Recommended 16:9; ~200KB.
           */
          image: string | Media;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'life-at-shanta';
      }
    | {
        uploadSessionId?: string | null;
        /**
         * Hex color in #RRGGBB (e.g., #FFFFFF). Length 7 (৭).
         */
        backgroundColor?: string | null;
        /**
         * Short, strong opener. Max 20 characters.
         */
        heading: string;
        /**
         * সংক্ষিপ্ত, শক্তিশালী সূচনা। সর্বোচ্চ ২০ অক্ষর।
         */
        headingBN: string;
        /**
         * Secondary line below the heading. Max 35 characters.
         */
        subheading: string;
        /**
         * শিরোনামের নিচে দ্বিতীয় লাইন। সর্বোচ্চ ৩৫ অক্ষর।
         */
        subheadingBN: string;
        /**
         * Lead-in title above the paragraph. Max 80 characters.
         */
        paragraphTitle: string;
        /**
         * অনুচ্ছেদের উপরে লিড-ইন শিরোনাম। সর্বোচ্চ ৮০ অক্ষর।
         */
        paragraphTitleBN: string;
        /**
         * Main descriptive text. Max 400 characters.
         */
        paragraph: string;
        /**
         * মূল বর্ণনামূলক টেক্সট। সর্বোচ্চ ৪০০ অক্ষর।
         */
        paragraphBN: string;
        /**
         * Primary visual for the intro section. 2.15:1 recommended.
         */
        image: string | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'shanta-intro';
      }
    | {
        /**
         * Large background visual for the section. 2.5:1 recommended.
         */
        bgImage: string | Media;
        /**
         * Primary heading for Vision. Max 14 characters.
         */
        visionTitle: string;
        /**
         * ভিশনের প্রধান শিরোনাম। সর্বোচ্চ ১৪ অক্ষর।
         */
        visionTitleBN: string;
        /**
         * Optional. Must appear inside the Vision Title exactly. Max 14 characters.
         */
        visionHighlightedText?: string | null;
        /**
         * ঐচ্ছিক। ভিশন শিরোনামের মধ্যে হুবহু থাকতে হবে। সর্বোচ্চ ১৪ অক্ষর।
         */
        visionHighlightedTextBN?: string | null;
        visionDescription: string;
        visionDescriptionBN: string;
        /**
         * Primary heading for Mission. Max 14 characters.
         */
        missionTitle: string;
        /**
         * মিশনের প্রধান শিরোনাম। সর্বোচ্চ ১৪ অক্ষর।
         */
        missionTitleBN: string;
        /**
         * Optional. Must appear inside the Mission Title exactly. Max 14 characters.
         */
        missionHighlightedText?: string | null;
        /**
         * ঐচ্ছিক। মিশন শিরোনামের মধ্যে হুবহু থাকতে হবে। সর্বোচ্চ ১৪ অক্ষর।
         */
        missionHighlightedTextBN?: string | null;
        missionDescription: string;
        missionDescriptionBN: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'shanta-vision';
      }
    | {
        /**
         * Hex color in #RRGGBB (e.g., #F6EDDD). Length 7 (৭).
         */
        backgroundColor?: string | null;
        /**
         * Base title (e.g., “Values That”). Max 40 characters.
         */
        title: string;
        /**
         * মূল শিরোনাম (যেমন, “আমাদের মূল্যবোধ”). সর্বোচ্চ ৪০ অক্ষর।
         */
        titleBN: string;
        /**
         * Highlighted tail of the heading (e.g., “Shape Us”). Must appear inside Title exactly. Max 40 characters.
         */
        highlightedText?: string | null;
        /**
         * শিরোনামের রঙিন অংশ (যেমন, “আমাদের পরিচয়”). এটি অবশ্যই শিরোনামের মধ্যে হুবহু থাকতে হবে। সর্বোচ্চ ৪০ অক্ষর।
         */
        highlightedTextBN?: string | null;
        /**
         * Large background image for the section. 2:3 recommended.
         */
        image: string | Media;
        /**
         * Add value items with icon + hover icon, a short title, and a brief description.
         */
        values: {
          /**
           * Icon shown normally. (give colored version and transparent bg image) (ratio 1:1)
           */
          image: string | Media;
          /**
           * Icon shown on hover. (give white version and transparent bg image) (ratio 1:1)
           */
          hoverImage: string | Media;
          /**
           * Short card title (e.g., “Trust”). Max 30 characters.
           */
          title: string;
          /**
           * সংক্ষিপ্ত কার্ড শিরোনাম (যেমন, “বিশ্বাস”). সর্বোচ্চ ৩০ অক্ষর।
           */
          titleBN: string;
          /**
           * Brief one-liner or two-liner. Max 150 characters.
           */
          description: string;
          /**
           * সংক্ষিপ্ত এক/দুই লাইনের বিবরণ। সর্বোচ্চ ১৫০ অক্ষর।
           */
          descriptionBN: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'values-that-shape-us';
      }
  )[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'resume';
        value: string | Resume;
      } | null)
    | ({
        relationTo: 'career-application';
        value: string | CareerApplication;
      } | null)
    | ({
        relationTo: 'agent-career-application';
        value: string | AgentCareerApplication;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  temporary?: T;
  ownerCollection?: T;
  ownerDocId?: T;
  ownerField?: T;
  derivedFrom?: T;
  blurDataURL?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume_select".
 */
export interface ResumeSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-application_select".
 */
export interface CareerApplicationSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  position?: T;
  message?: T;
  resume?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-career-application_select".
 */
export interface AgentCareerApplicationSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  resume?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  uploadSessionId?: T;
  name?: T;
  slug?: T;
  publish?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              uploadSessionId?: T;
              heroes?:
                | T
                | {
                    image?: T;
                    title?: T;
                    titleBN?: T;
                    subtitle?: T;
                    subtitleBN?: T;
                    description?: T;
                    descriptionBN?: T;
                    id?: T;
                  };
              ctaButtons?:
                | T
                | {
                    pageLink?:
                      | T
                      | {
                          label?: T;
                          labelBN?: T;
                          page?: T;
                          style?: T;
                          id?: T;
                          blockName?: T;
                        };
                    youtubeVideo?:
                      | T
                      | {
                          label?: T;
                          labelBN?: T;
                          youtubeUrl?: T;
                          id?: T;
                          blockName?: T;
                        };
                    callNow?:
                      | T
                      | {
                          label?: T;
                          labelBN?: T;
                          phoneNumber?: T;
                          style?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        'why-choose-us'?:
          | T
          | {
              backgroundColor?: T;
              heading?: T;
              headingBN?: T;
              title?: T;
              titleBN?: T;
              subtitle?: T;
              subtitleBN?: T;
              highlightedText?: T;
              highlightedTextBN?: T;
              description?: T;
              descriptionBN?: T;
              mainImage?: T;
              sideImage?: T;
              stats?:
                | T
                | {
                    icon?: T;
                    label?: T;
                    labelBN?: T;
                    value?: T;
                    valueBN?: T;
                    id?: T;
                  };
              buttonText?: T;
              buttonTextBN?: T;
              buttonLink?: T;
              id?: T;
              blockName?: T;
            };
        'featured-plans'?:
          | T
          | {
              backgroundColor?: T;
              heading?: T;
              headingBN?: T;
              title?: T;
              titleBN?: T;
              highlightedText?: T;
              highlightedTextBN?: T;
              description?: T;
              descriptionBN?: T;
              plans?:
                | T
                | {
                    icon?: T;
                    image?: T;
                    title?: T;
                    titleBN?: T;
                    subtitle?: T;
                    subtitleBN?: T;
                    description?: T;
                    descriptionBN?: T;
                    plansButtonText?: T;
                    plansButtonTextBN?: T;
                    plansButtonLink?: T;
                    id?: T;
                  };
              buttonText?: T;
              buttonTextBN?: T;
              buttonLink?: T;
              id?: T;
              blockName?: T;
            };
        'home-premium-calculator'?:
          | T
          | {
              backgroundColor?: T;
              heading?: T;
              headingBN?: T;
              title?: T;
              titleBN?: T;
              highlightedText?: T;
              highlightedTextBN?: T;
              description?: T;
              descriptionBN?: T;
              backgroundImage1?: T;
              backgroundImage2?: T;
              id?: T;
              blockName?: T;
            };
        'life-insurance-simplified'?:
          | T
          | {
              backgroundColor?: T;
              sectionHeading?: T;
              sectionHeadingBN?: T;
              sectionHeadingHighlightedText?: T;
              sectionHeadingHighlightedTextBN?: T;
              sections?:
                | T
                | {
                    title?: T;
                    titleBN?: T;
                    titleHighlightedText?: T;
                    titleHighlightedTextBN?: T;
                    subtitle?: T;
                    subtitleBN?: T;
                    mainVIdeoLink?: T;
                    mainImage?: T;
                    insuranceCardData?:
                      | T
                      | {
                          image?: T;
                          title?: T;
                          titleBN?: T;
                          description?: T;
                          descriptionBN?: T;
                          videoLink?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'home-video'?:
          | T
          | {
              backgroundColor?: T;
              title?: T;
              titleBN?: T;
              highlightedText?: T;
              highlightedTextBN?: T;
              backgroundVideoUrl?: T;
              youtubeUrl?: T;
              youtubeButtonText?: T;
              youtubeButtonTextBN?: T;
              thumbnail?: T;
              id?: T;
              blockName?: T;
            };
        'life-at-shanta'?:
          | T
          | {
              backgroundColor?: T;
              title?: T;
              titleBN?: T;
              subtitle?: T;
              subtitleBN?: T;
              highlightedSubtitle?: T;
              highlightedSubtitleBN?: T;
              description?: T;
              descriptionBN?: T;
              buttonText?: T;
              buttonTextBN?: T;
              buttonLink?: T;
              backgroundImage?: T;
              gallery?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'shanta-intro'?:
          | T
          | {
              uploadSessionId?: T;
              backgroundColor?: T;
              heading?: T;
              headingBN?: T;
              subheading?: T;
              subheadingBN?: T;
              paragraphTitle?: T;
              paragraphTitleBN?: T;
              paragraph?: T;
              paragraphBN?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        'shanta-vision'?:
          | T
          | {
              bgImage?: T;
              visionTitle?: T;
              visionTitleBN?: T;
              visionHighlightedText?: T;
              visionHighlightedTextBN?: T;
              visionDescription?: T;
              visionDescriptionBN?: T;
              missionTitle?: T;
              missionTitleBN?: T;
              missionHighlightedText?: T;
              missionHighlightedTextBN?: T;
              missionDescription?: T;
              missionDescriptionBN?: T;
              id?: T;
              blockName?: T;
            };
        'values-that-shape-us'?:
          | T
          | {
              backgroundColor?: T;
              title?: T;
              titleBN?: T;
              highlightedText?: T;
              highlightedTextBN?: T;
              image?: T;
              values?:
                | T
                | {
                    image?: T;
                    hoverImage?: T;
                    title?: T;
                    titleBN?: T;
                    description?: T;
                    descriptionBN?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Top strip above navbar: flat set of links (non-nested) and whether to show the language toggle.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "global-header".
 */
export interface GlobalHeader {
  id: string;
  /**
   * Add simple links for the top header. No nesting. Each link has EN/BN label and a URL/path.
   */
  links?:
    | {
        /**
         * Max 60 chars (৬০).
         */
        label: string;
        /**
         * সর্বোচ্চ ৬০ অক্ষর।
         */
        labelBN: string;
        /**
         * Starts with "/" or a full http(s) URL. Max 300 chars (৩০০).
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Enable / disable the language switcher in the top header.
   */
  showLocalizationToggle?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Global navbar: logo and multi-level navigation (desktop & mobile), plus an optional portal link.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "global-navbar".
 */
export interface GlobalNavbar {
  id: string;
  branding: {
    /**
     * Primary logo shown in the navbar. Recommended transparent PNG/SVG.
     */
    logo: string | Media;
  };
  desktop?: {
    /**
     * Top-level nav items for desktop. Each item can optionally have nested children.
     */
    items?:
      | {
          /**
           * Max 40 chars (৪০).
           */
          label: string;
          /**
           * সর্বোচ্চ ৪০ অক্ষর।
           */
          labelBN: string;
          /**
           * Use "#", start with "/", or a full http(s) URL. Max 300 chars (৩০০).
           */
          href: string;
          /**
           * Optional submenu items. You can nest up to 5 levels.
           */
          children?:
            | {
                /**
                 * Max 40 chars (৪০).
                 */
                label: string;
                /**
                 * সর্বোচ্চ ৪০ অক্ষর।
                 */
                labelBN: string;
                /**
                 * Use "#", start with "/", or a full http(s) URL. Max 300 chars (৩০০).
                 */
                href: string;
                /**
                 * Optional submenu items. You can nest up to 5 levels.
                 */
                children?:
                  | {
                      /**
                       * Max 40 chars (৪০).
                       */
                      label: string;
                      /**
                       * সর্বোচ্চ ৪০ অক্ষর।
                       */
                      labelBN: string;
                      /**
                       * Use "#", start with "/", or a full http(s) URL. Max 300 chars (৩০০).
                       */
                      href: string;
                      /**
                       * Optional submenu items. You can nest up to 5 levels.
                       */
                      children?:
                        | {
                            /**
                             * Max 40 chars (৪০).
                             */
                            label: string;
                            /**
                             * সর্বোচ্চ ৪০ অক্ষর।
                             */
                            labelBN: string;
                            /**
                             * Use "#", start with "/", or a full http(s) URL. Max 300 chars (৩০০).
                             */
                            href: string;
                            /**
                             * Optional submenu items. You can nest up to 5 levels.
                             */
                            children?:
                              | {
                                  /**
                                   * Max 40 chars (৪০).
                                   */
                                  label: string;
                                  /**
                                   * সর্বোচ্চ ৪০ অক্ষর।
                                   */
                                  labelBN: string;
                                  /**
                                   * Use "#", start with "/", or a full http(s) URL. Max 300 chars (৩০০).
                                   */
                                  href: string;
                                  id?: string | null;
                                }[]
                              | null;
                            id?: string | null;
                          }[]
                        | null;
                      id?: string | null;
                    }[]
                  | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  mobile?: {
    /**
     * Mobile menu items. Often mirrors desktop, but can differ if needed (ordering, labels, etc.).
     */
    items?:
      | {
          /**
           * Max 40 chars (৪০).
           */
          label: string;
          /**
           * সর্বোচ্চ ৪০ অক্ষর।
           */
          labelBN: string;
          /**
           * Use "#", start with "/", or a full http(s) URL. Max 300 chars (৩০০).
           */
          href: string;
          /**
           * Optional submenu items. You can nest up to 5 levels.
           */
          children?:
            | {
                /**
                 * Max 40 chars (৪০).
                 */
                label: string;
                /**
                 * সর্বোচ্চ ৪০ অক্ষর।
                 */
                labelBN: string;
                /**
                 * Use "#", start with "/", or a full http(s) URL. Max 300 chars (৩০০).
                 */
                href: string;
                /**
                 * Optional submenu items. You can nest up to 5 levels.
                 */
                children?:
                  | {
                      /**
                       * Max 40 chars (৪০).
                       */
                      label: string;
                      /**
                       * সর্বোচ্চ ৪০ অক্ষর।
                       */
                      labelBN: string;
                      /**
                       * Use "#", start with "/", or a full http(s) URL. Max 300 chars (৩০০).
                       */
                      href: string;
                      /**
                       * Optional submenu items. You can nest up to 5 levels.
                       */
                      children?:
                        | {
                            /**
                             * Max 40 chars (৪০).
                             */
                            label: string;
                            /**
                             * সর্বোচ্চ ৪০ অক্ষর।
                             */
                            labelBN: string;
                            /**
                             * Use "#", start with "/", or a full http(s) URL. Max 300 chars (৩০০).
                             */
                            href: string;
                            /**
                             * Optional submenu items. You can nest up to 5 levels.
                             */
                            children?:
                              | {
                                  /**
                                   * Max 40 chars (৪০).
                                   */
                                  label: string;
                                  /**
                                   * সর্বোচ্চ ৪০ অক্ষর।
                                   */
                                  labelBN: string;
                                  /**
                                   * Use "#", start with "/", or a full http(s) URL. Max 300 chars (৩০০).
                                   */
                                  href: string;
                                  id?: string | null;
                                }[]
                              | null;
                            id?: string | null;
                          }[]
                        | null;
                      id?: string | null;
                    }[]
                  | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Optional action link (e.g., “My Portal”) on the right in desktop.
   */
  portal?: {
    /**
     * Max 40 chars (৪০).
     */
    label?: string | null;
    /**
     * সর্বোচ্চ ৪০ অক্ষর।
     */
    labelBN?: string | null;
    /**
     * "#", internal path ("/…"), or full http(s) URL. Max 300 chars (৩০০).
     */
    href?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Site-wide footer: logo & contact, Explore & Legal links, Social URLs, and Copyright.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "global-footer".
 */
export interface GlobalFooter {
  id: string;
  /**
   * Footer logo and basic contact details shown at the top of the footer.
   */
  branding: {
    /**
     * Primary footer logo. Recommended square, ~50KB.
     */
    logo: string | Media;
    email: string;
    /**
     * Public Google Maps link to your location. Must be an absolute http(s) URL.
     */
    mapUrl: string;
    phone: string;
    /**
     * বাংলা নম্বরে দিতে পারেন। সর্বোচ্চ ৪০ অক্ষর।
     */
    phoneBN: string;
    /**
     * Shown under the phone number (optional). Max 80 chars (৮০).
     */
    phoneNote?: string | null;
    /**
     * ফোন নম্বরের নিচে দেখানো হবে (ঐচ্ছিক)। সর্বোচ্চ ৮০ অক্ষর।
     */
    phoneNoteBN?: string | null;
    /**
     * Mailing/visit address. Max 200 chars (২০০).
     */
    address: string;
    /**
     * বাংলায় ঠিকানা। সর্বোচ্চ ২০০ অক্ষর।
     */
    addressBN: string;
  };
  /**
   * Header + links for the “Explore” column. Internal paths (e.g., /plans) or full http(s) URLs.
   */
  exploreSection: {
    /**
     * Overrides the Explore column title. Max 40 chars (৪০).
     */
    exploreHeader: string;
    /**
     * Explore কলামের শিরোনাম। সর্বোচ্চ ৪০ অক্ষর।
     */
    exploreHeaderBN: string;
    explore?:
      | {
          /**
           * Max 40 chars (৪০).
           */
          label: string;
          /**
           * সর্বোচ্চ ৪০ অক্ষর।
           */
          labelBN: string;
          /**
           * Starts with "/" or a full http(s) URL. Max 300 chars (৩০০).
           */
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Header + links for the “Legal” column (e.g., Privacy Policy, Terms). Internal paths or full http(s) URLs.
   */
  legalSection?: {
    /**
     * Overrides the Legal column title. Max 40 chars (৪০).
     */
    legalHeader?: string | null;
    /**
     * Legal কলামের শিরোনাম। সর্বোচ্চ ৪০ অক্ষর।
     */
    legalHeaderBN?: string | null;
    /**
     * Links for the “Legal” column (e.g., Privacy Policy, Terms). Internal paths or http(s) URLs.
     */
    legal?:
      | {
          /**
           * Max 40 chars (৪০).
           */
          label: string;
          /**
           * সর্বোচ্চ ৪০ অক্ষর।
           */
          labelBN: string;
          /**
           * Starts with "/" or a full http(s) URL. Max 300 chars (৩০০).
           */
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Section header + public social profile links (must be absolute http(s) URLs).
   */
  social: {
    /**
     * Overrides the Social column title. Max 40 chars (৪০).
     */
    socialHeader?: string | null;
    /**
     * Social কলামের শিরোনাম। সর্বোচ্চ ৪০ অক্ষর।
     */
    socialHeaderBN?: string | null;
    facebookUrl: string;
    youtubeUrl: string;
    linkedinUrl: string;
    instagramUrl: string;
  };
  /**
   * Main copyright line. Max 200 chars (২০০).
   */
  copyright: string;
  /**
   * বাংলা কপিরাইট টেক্সট। সর্বোচ্চ ২০০ অক্ষর।
   */
  copyrightBN: string;
  /**
   * Optional; must appear verbatim inside Copyright. Max 120 chars (১২০).
   */
  copyrightHighlightedText?: string | null;
  /**
   * ঐচ্ছিক; কপিরাইট (বাংলা)-এর মধ্যে হুবহু থাকতে হবে। সর্বোচ্চ ১২০ অক্ষর।
   */
  copyrightHighlightedTextBN?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "global-header_select".
 */
export interface GlobalHeaderSelect<T extends boolean = true> {
  links?:
    | T
    | {
        label?: T;
        labelBN?: T;
        href?: T;
        id?: T;
      };
  showLocalizationToggle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "global-navbar_select".
 */
export interface GlobalNavbarSelect<T extends boolean = true> {
  branding?:
    | T
    | {
        logo?: T;
      };
  desktop?:
    | T
    | {
        items?:
          | T
          | {
              label?: T;
              labelBN?: T;
              href?: T;
              children?:
                | T
                | {
                    label?: T;
                    labelBN?: T;
                    href?: T;
                    children?:
                      | T
                      | {
                          label?: T;
                          labelBN?: T;
                          href?: T;
                          children?:
                            | T
                            | {
                                label?: T;
                                labelBN?: T;
                                href?: T;
                                children?:
                                  | T
                                  | {
                                      label?: T;
                                      labelBN?: T;
                                      href?: T;
                                      id?: T;
                                    };
                                id?: T;
                              };
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
            };
      };
  mobile?:
    | T
    | {
        items?:
          | T
          | {
              label?: T;
              labelBN?: T;
              href?: T;
              children?:
                | T
                | {
                    label?: T;
                    labelBN?: T;
                    href?: T;
                    children?:
                      | T
                      | {
                          label?: T;
                          labelBN?: T;
                          href?: T;
                          children?:
                            | T
                            | {
                                label?: T;
                                labelBN?: T;
                                href?: T;
                                children?:
                                  | T
                                  | {
                                      label?: T;
                                      labelBN?: T;
                                      href?: T;
                                      id?: T;
                                    };
                                id?: T;
                              };
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
            };
      };
  portal?:
    | T
    | {
        label?: T;
        labelBN?: T;
        href?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "global-footer_select".
 */
export interface GlobalFooterSelect<T extends boolean = true> {
  branding?:
    | T
    | {
        logo?: T;
        email?: T;
        mapUrl?: T;
        phone?: T;
        phoneBN?: T;
        phoneNote?: T;
        phoneNoteBN?: T;
        address?: T;
        addressBN?: T;
      };
  exploreSection?:
    | T
    | {
        exploreHeader?: T;
        exploreHeaderBN?: T;
        explore?:
          | T
          | {
              label?: T;
              labelBN?: T;
              url?: T;
              id?: T;
            };
      };
  legalSection?:
    | T
    | {
        legalHeader?: T;
        legalHeaderBN?: T;
        legal?:
          | T
          | {
              label?: T;
              labelBN?: T;
              url?: T;
              id?: T;
            };
      };
  social?:
    | T
    | {
        socialHeader?: T;
        socialHeaderBN?: T;
        facebookUrl?: T;
        youtubeUrl?: T;
        linkedinUrl?: T;
        instagramUrl?: T;
      };
  copyright?: T;
  copyrightBN?: T;
  copyrightHighlightedText?: T;
  copyrightHighlightedTextBN?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}