name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
      - staging

jobs:
  build_and_deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create .env from ENV_FILE secret
        run: |
          cat > .env << 'EOF'
          ${{ secrets.ENV_FILE }}
          EOF

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          IMAGE_TAG=$(git rev-parse --short HEAD)
          if ${{ github.ref == 'refs/heads/main' }}; then
            BRANCH='main'
          else
            BRANCH='staging'
          fi

          docker build --progress=plain \
            -f Dockerfile \
            -t shantalife:$IMAGE_TAG \
            -t shantalife:$BRANCH-latest .

      - name: Deploy to servers
        run: |
          IMAGE_TAG=$(git rev-parse --short HEAD)

          if ${{ github.ref == 'refs/heads/main' }}; then
            BRANCH='main'
            PORT=${{ secrets.SERVER_PORT_MAIN }}
          else
            BRANCH='staging'
            PORT=${{ secrets.SERVER_PORT_STAGING }}
          fi

          mkdir -p ~/.ssh/shanta-life
          printf "%s\n" "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/shanta-life/id_rsa
          chmod 600 ~/.ssh/shanta-life/id_rsa

          docker save -o shantalife.tar shantalife:$IMAGE_TAG shantalife:$BRANCH-latest

          for SERVER_IP in $(echo ${{ secrets.SERVER_IP_LIST }} | tr ',' '\n'); do
            echo "Deploying to $SERVER_IP"

            ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

            scp -i ~/.ssh/shanta-life/id_rsa shantalife.tar ubuntu@$SERVER_IP:/tmp

            ssh -i ~/.ssh/shanta-life/id_rsa ubuntu@$SERVER_IP <<EOF
              docker images -q --filter "reference=shantalife" | xargs -r docker rmi -f
              docker load -i /tmp/shantalife.tar
              docker ps -q --filter name=shantalife-$BRANCH | xargs -r docker stop
              docker ps -a -q --filter "name=shantalife-$BRANCH" | xargs -r docker rm

              docker run -d -p ${{ secrets.PORT }}:3000 --name shantalife-$BRANCH shantalife:$BRANCH-latest

              docker image prune -a -f

              rm -f /tmp/shantalife.tar
          EOF
          done

          rm -f ~/.ssh/shanta-life/id_rsa
          rm -f shantalife.tar

          docker images -q --filter "dangling=true" | xargs -r docker rmi
          docker images -q --filter "reference=shantalife" | xargs -r docker rmi
          docker container prune -f
          docker volume ls -q --filter dangling=true | xargs -r docker volume rm
